# Generated by Django 3.1.3 on 2020-12-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='points',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='remarks',
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_user.employee')),
            ],
        ),
    ]
