# Generated by Django 3.1.3 on 2020-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
