# Generated by Django 3.1.3 on 2020-12-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0002_auto_20201205_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
