# Generated by Django 3.1.4 on 2020-12-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0003_house_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='points',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rank',
        ),
    ]
