# Generated by Django 3.1.4 on 2020-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0004_auto_20201214_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
