# Generated by Django 3.1.4 on 2020-12-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0005_auto_20201214_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='points',
        ),
    ]
