# Generated by Django 3.1.4 on 2020-12-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0006_remove_house_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
