# Generated by Django 3.1.4 on 2020-12-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0007_house_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='point',
        ),
    ]
